server:
  port: 8044

spring:
  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      authentication-database: admin
      #      username: root
      #      password: root
      database: librarydb
      port: 27017
      host: localhost

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2



mongock:

  change-logs-scan-package:
    - ru.otus.spring.shepin.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: info
    de.flapdoodle.os.common.attributes: warn