server:
  port: 8082

spring:

  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: librarydb
      port: 27017
      host: localhost

  shell:
    interactive:
      enabled: false
    command:
      stacktrace:
        enabled: true

mongock:
  runner-type: "Applicationrunner"
  #runner-type: "InitializingBean"  # если раскомментить- будет работать с shell
  change-logs-scan-package:
    - ru.otus.spring.shepin.mongock.changelog

logging:
  level:
    ROOT: ERROR