stream:
  output: T(System).out
  input: T(System).in

test:
  locale: ru_RU
  file-name: Questions.csv
  minRightAnswer: 3

#--------------------------------------
spring:
  banner:
    location: classpath:/banner/myBanner.txt
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

management:
  endpoints:
    web:
      exposure:
        include: info, health, bean

server:
  port: 8081

