spring:

  datasource:
    url: jdbc:h2:mem:librarydb
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false
    sql:
      init:
       mode: always
       data-locations: data.sql

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  shell:
    interactive:
      enabled: false
    command:
      stacktrace:
        enabled: true


server:
  port: 8082

logging:
  level:
    ROOT: ERROR