server:
  port: 8045

spring:
  application:
    name: acceptance-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5404/library_db
    sql:
      init:
        mode: always # при запуске выполнять скрипт data.sql, который заполняет данными таблицы
    username: root
    password: root

  jpa:
    show-sql: true #    показывает запросы в консоли
    generate-ddl: false
    hibernate:
      ddl-auto: none # eсли значение create, то hibernate сам создаст таблицы

    properties:
      hibernate:
        format_sql: true  # отображение скриптов создания таблиц в консоли, если значение true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


logging:
  level:
    ROOT: ERROR